Repository DIT112-V20/group-09, pull requests merged in 2020-04, with the labels that each got.

#10 [README] Bugfix: missing command in the build instructions
  README.md
Labels: bug, documentation

#15 ArduinoCLI preprocessing
  CMakeLists.txt
  include/ardpolyfills/Arduino.h
  modules/CMakeLists.txt
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/include/ardrivo/entrypoint.hxx
  modules/ardrivo/src/entrypoint.cxx
  modules/ardrivo/test/entrypoint.cxx
  modules/trycompile/CMakeLists.txt
  modules/trycompile/include/trycompile/Toolchain.hxx
  modules/trycompile/src/Toolchain.cxx
  modules/trycompile/test/compile.cxx
  modules/trycompile/test/load.cxx
  share/CMakeLists.txt
  share/Fragments/symbols.cxx
  share/Modules/Preproc.cmake
Labels: enhancement, extra

#17 Better share
  CMakeLists.txt
  modules/trycompile/src/Toolchain.cxx
  share/smce/toolchain/CMakeLists.txt
  share/smce/toolchain/Fragments/symbols.cxx
  share/smce/toolchain/Modules/Preproc.cmake
Labels: extra

#28 [CI] macOS clang-10: fix broken bottle
  .github/workflows/ccpp.yml
Labels: bug, ci

#31 [Ardrivo] bugfixes in HardwareSerial and String
  include/ardpolyfills/Print.h
  include/ardpolyfills/WString.h
  modules/ardrivo/src/HardwareSerial.cxx
  modules/ardrivo/src/String.cxx
Labels: bug

#32 Adding BoardConfig to configloader
  CMake/Modules/Patcher.cmake
  CMake/Modules/SetupUrho3D.cmake
  CMakeLists.txt
  modules/configloader/CMakeLists.txt
  modules/configloader/include/configloader/BoardConf.hxx
  modules/configloader/include/configloader/ProgramOptions.hxx
  modules/configloader/src/BoardConf.cxx
  modules/configloader/src/BoardConfSchema.cxx
  modules/configloader/src/ProgramOptions.cxx
  modules/configloader/test/BoardConf.cxx
  modules/configloader/test/load.cxx
Labels: sprint-2

#43 Handle dynamic init IO
  .github/workflows/ccpp.yml
  include/utility.hxx
  modules/ardrivo/include/ardrivo/Entrypoint.hxx
  modules/ardrivo/src/Arduino.cxx
  modules/ardrivo/src/Entrypoint.cxx
  modules/ardrivo/src/HardwareSerial.cxx
Labels: bug

#38 Current wire implementation
  include/BoardData.hxx
  include/ardpolyfills/Wire.h
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/src/Arduino.cxx
  modules/ardrivo/src/Wire.cxx
Labels: sprint-2

#36 Servo implementation
  include/ardpolyfills/Servo.h
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/src/Servo.cxx
  modules/ardrivo/test/Servo.cxx
Labels: sprint-2
