Repository DIT112-V20/group-09, pull requests merged in 2020-05, with the labels that each got.

#48 Vehicle config
  CMakeLists.txt
  include/app/UrhoApp.hxx
  include/components/Registry.hxx
  modules/configloader/CMakeLists.txt
  modules/configloader/include/configloader/ConfHelper.hxx
  modules/configloader/include/configloader/VehicleConf.hxx
  modules/configloader/src/BoardConf.cxx
  modules/configloader/src/VehicleConf.cxx
  modules/configloader/test/VehicleConf.cxx
  src/app/UrhoApp.cxx
Labels: sprint-3

#49 Arduino SPI library
  CMake/Modules/StdPolyfills.cmake
  include/BoardData.hxx
  include/BoardInfo.hxx
  include/ardpolyfills/SPI.h
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/src/Entrypoint.cxx
  modules/ardrivo/src/SPI.cxx
  modules/ardrivo/test/CatchMain.cxx
  modules/ardrivo/test/Entrypoint.cxx
  modules/ardrivo/test/SPI.cxx
  modules/ardrivo/test/Servo.cxx
Labels: extra

#50 I2C give each slave access to their own buffer
  include/BoardData.hxx
  modules/ardrivo/src/Entrypoint.cxx
  modules/ardrivo/src/Wire.cxx
Labels: bug

#56 Package I2C transmissions
  include/BoardData.hxx
  modules/ardrivo/src/Wire.cxx
Labels: enhancement

#58 [ardrivo] Don't reset i2c slave_address in endTransmission
  modules/ardrivo/src/Wire.cxx
Labels: bug

#63 Add interrupt backend
  CMake/Check/has_libcxx.cpp
  CMake/Check/has_libstdcxx.cpp
  CMake/Modules/StdPolyfills.cmake
  include/BoardData.hxx
  include/ardpolyfills/Arduino.h
  include/utility.hxx
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/src/Arduino.cxx
  modules/ardrivo/src/HardwareSerial.cxx
  modules/ardrivo/src/ProtectedAlloc.cxx
  modules/ardrivo/src/SPI.cxx
  modules/ardrivo/test/SPI.cxx
  modules/ardrivo/test/Servo.cxx
  modules/configloader/src/BoardConf.cxx
  modules/trycompile/CMakeLists.txt
  modules/trycompile/include/trycompile/Runtime.hxx
  modules/trycompile/include/trycompile/detail/Interrupt.hxx
  modules/trycompile/src/Interrupt.cxx
  modules/trycompile/src/Runtime.cxx
  modules/trycompile/test/interrupt.cxx
Labels: sprint-5

#69 Interrupts fataly unstable
  .github/workflows/ccpp.yml
  CMake/Modules/StdPolyfills.cmake
  modules/ardrivo/CMakeLists.txt
  modules/trycompile/include/trycompile/Runtime.hxx
  modules/trycompile/include/trycompile/detail/Interrupt.hxx
  modules/trycompile/src/Interrupt.cxx
  modules/trycompile/src/Runtime.cxx
  modules/trycompile/test/interrupt.cxx
Labels: bug

#75 [Ardpolyfills] fix missing include
  include/ardpolyfills/Arduino.h
Labels: bug

#76 [ardrivo] Add missing definition for global Arduino symbol `Wire`
  modules/ardrivo/src/Wire.cxx
Labels: bug

#62 Implement GUI frontend + Backend
  CMakeLists.txt
  include/app/UrhoApp.hxx
  include/components/EmulGlue.hxx
  include/components/MovableCamera.hxx
  include/components/Registry.hxx
  include/gui/TorchEvents.hxx
  include/gui/TorchMenu.hxx
  modules/ardrivo/include/ardrivo/Entrypoint.hxx
  modules/ardrivo/src/Entrypoint.cxx
  modules/configloader/CMakeLists.txt
  modules/configloader/include/configloader/ProgramOptions.hxx
  modules/configloader/src/ProgramOptions.cxx
  modules/configloader/test/load.cxx
  modules/trycompile/include/trycompile/Object.hxx
  modules/trycompile/include/trycompile/Runtime.hxx
  modules/trycompile/src/Object.cxx
  modules/trycompile/src/Runtime.cxx
  modules/trycompile/src/Toolchain.cxx
  share/smce/Torch/Torch/Data/Fonts/Roboto Mono.ttf
  share/smce/Torch/Torch/Data/Fonts/Roboto.ttf
  share/smce/Torch/Torch/Data/Textures/UI.png
  share/smce/Torch/Torch/Data/UI/TorchOverlay.xml
  share/smce/Torch/Torch/Data/UI/TorchPopup.xml
  share/smce/Torch/Torch/Data/UI/TorchSettings.xml
  share/smce/Torch/Torch/Data/UI/TorchStyle.xml
  share/smce/toolchain/Fragments/symbols.cxx
  src/app/UrhoApp.cxx
  src/components/EmulGlue.cxx
  src/components/MovableCamera.cxx
  src/gui/TorchMenu.cxx
Labels: sprint-3, sprint-6

#86 Remove unwanted and useless header-dependency chain
  include/ardpolyfills/Wire.h
Labels: bug

#87 Ardrivo fixes
  include/components/EmulGlue.hxx
  modules/ardrivo/src/Arduino.cxx
  modules/ardrivo/src/String.cxx
  modules/ardrivo/test/SPI.cxx
  modules/ardrivo/test/Servo.cxx
Labels: bug

#78 Wire test
  modules/ardrivo/CMakeLists.txt
  modules/ardrivo/src/Wire.cxx
  modules/ardrivo/test/Wire.cxx
Labels: sprint-4

#88 Fancy environment
  CMakeSettings.json
  include/components/MovableCamera.hxx
  modules/configloader/include/configloader/ProgramOptions.hxx
  modules/configloader/src/ProgramOptions.cxx
  share/smce/Torch/Torch/Data/VirtualEnvironment/smartCarEnvironment.xml
  src/app/UrhoApp.cxx
  src/gui/TorchMenu.cxx
Labels: sprint-7
